runtime: python27
api_version: 1
threadsafe: yes

inbound_services:
- mail

handlers:
- url: /_ah/mail/[a-z\-]+@votemesir\.appspotmail\.com
  script: handle_receiver.app
  login: admin

- url: /.*
  script: main.app

- includes:
  skip_files: app_includes/skip_files.yaml
