runtime: python27
api_version: 1
threadsafe: yes

inbound_services:
- mail

handlers:
- url: /_ah/mail/[a-z\-]+@voteme-sir\.appspotmail\.com
  script: main.app
  login: admin

- url: /.*
  script: main.app

includes:
- app_includes/skip_files.yaml
